name: Zville
favicon: null
layout_spectrum: 0.8684749840758741
typography_spectrum: 0.7888485072180629
title: 'Zville- The Place for Health, Wellness and everything to Live Life Unlimited'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f5e00'
    - '#010300'
    - '#79965e'
    - '#e0e3de'
    - '#f06500'
  brandStrength: 0.6875
  lightness: 0.9408600826282054
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
